version: '3'

services:

  arango:
    container_name: arango
    image: arangodb/arangodb:3.7.2
    restart: always
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=openSesame
    volumes:
      - ~/arangodb:/var/lib/arangodb3

  google-reviews:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    image: google-reviews
    volumes:
      - ./:/code
    env_file:
      - ./compose/env
    ports:
      - 80:80
    links:
      - arango
